[project]
name = "pyHostService"
version = "0.0.1"
dependencies = [
    "numpy",
    "pycryptodomex",
    "crcmod",
    "pyserial",
    "gooey",
]
[project.scripts]
pyhost = "pyHostService:main"
pyhost-cli = "pyHostService:main_cli"