[project]
name = "pyHostService"
version = "0.0.1"
dependencies = [
    "numpy",
    "pycryptodomex",
    "crcmod",
    "pyserial",
    "pyserial-asyncio",
    "gooey",
]
[project.scripts]
pyHostService = "pyHostService:main"